/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tablet.gltf --transform
Author: atomle (https://sketchfab.com/atomle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ipad-7-ec2b3966d0384f87bfdff55799778bf0
Title: Ipad 7
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props:any) {
  const { nodes, materials }:any = useGLTF('/tablet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.49}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.WhlxbaYfsXeMUCt.geometry} material={materials.isbqkijGoNYDTxF} />
          <mesh geometry={nodes.aECxmXbZEIzGUHM.geometry} material={materials.gOzKWfldoAhClOI} />
          <mesh geometry={nodes.kyqgosGwBQpScsG.geometry} material={materials.qlZPKxBFgZdoAjL} />
          <mesh geometry={nodes.mndrlEbtVdHhGMo.geometry} material={materials.isbqkijGoNYDTxF} />
          <mesh geometry={nodes.NgCgolCaNjqjcGZ.geometry} material={materials.gABZztNTvVoXmXc} />
          <mesh geometry={nodes.AqQKRyrpQwgBryg.geometry} material={materials.qPdRArWhuRLRGFi} />
          <mesh geometry={nodes.wAhMcFfKTtyzNzi.geometry} material={materials.LmzdlAXwDtjIPEa} />
          <mesh geometry={nodes.QxDDcFPFhLQFsSG.geometry} material={materials.yaLBQePStnlbxkc} />
          <mesh geometry={nodes.ysTUozDdizWVQXV.geometry} material={materials.isbqkijGoNYDTxF} />
          <mesh geometry={nodes.nwcHCuwxdKpCgWo.geometry} material={materials.TMaMJjIPkqFqacG} />
          <mesh geometry={nodes.gdeJKIhJXINgrYh.geometry} material={materials.lIbmhnHcRxCyKTH} />
          <mesh geometry={nodes.ArWKwJjfhxVbBMW.geometry} material={materials.qlZPKxBFgZdoAjL} />
          <mesh geometry={nodes.PIzugUUCVUOfcMk.geometry} material={materials.JQuejxSwmuFbDqi} />
          <mesh geometry={nodes.LhdDpZTaoXzvEEj.geometry} material={materials.xiLgcDwUCBmXkPy} />
          <mesh geometry={nodes.LzcuanfYWpHCipQ.geometry} material={materials.xiLgcDwUCBmXkPy} />
          <mesh geometry={nodes.kvzPWODtCYjxUHV.geometry} material={materials.qPdRArWhuRLRGFi} />
          <mesh geometry={nodes.iXEWIfpTRTyEAmy.geometry} material={materials.xiLgcDwUCBmXkPy} />
          <mesh geometry={nodes.kCmxqEsUEZeCgVi.geometry} material={materials.xiLgcDwUCBmXkPy} />
          <mesh geometry={nodes.nbwVSADQhYNDTpG.geometry} material={materials.qPdRArWhuRLRGFi} />
          <mesh geometry={nodes.pEEytdBMnHnGyHf.geometry} material={materials.fxxucOdZGHHXkYk} />
          <mesh geometry={nodes.WjRjdgofilNQBSw.geometry} material={materials.yOrtZNlfOvvxPSM} />
          <mesh geometry={nodes.PAAoyRECyjFHYme.geometry} material={materials.vVXWFKSmigZlowN} />
          <mesh geometry={nodes.KrwCNcMwboPgCok.geometry} material={materials.TTqkrhlXHkdrldy} />
          <mesh geometry={nodes.azGKOzbkDXvKAGK.geometry} material={materials.JQuejxSwmuFbDqi} />
          <mesh geometry={nodes.WYHnWFgKtNXpiYQ.geometry} material={materials.qQZEgslfSFKUScB} />
          <mesh geometry={nodes.tWPGnTQcSWOELFw.geometry} material={materials.eTUqMdUiJziCRoV} />
          <mesh geometry={nodes.mTkNfzhZGYVeHtw.geometry} material={materials.yOrtZNlfOvvxPSM} />
          <mesh geometry={nodes.fHauwxoIEFKtvOx.geometry} material={materials.vVXWFKSmigZlowN} />
          <mesh geometry={nodes.gHBUFtXsGrwMOmY.geometry} material={materials.TTqkrhlXHkdrldy} />
          <mesh geometry={nodes.ajubXvpUTWnWmDu_0.geometry} material={materials.JQuejxSwmuFbDqi} />
          <mesh geometry={nodes.OUJxSIJrLYNmldQ.geometry} material={materials.yRJLRfFCjLbxLIu} />
          <mesh geometry={nodes.uEpLYkIjrrbqcef.geometry} material={materials.WiLZDKmGOAGYwwJ} />
          <mesh geometry={nodes.pZOyelrgjGrmZfx.geometry} material={materials.jypBaSgBJwGTeBs} />
          <mesh geometry={nodes.arETawMxPjZCMEa.geometry} material={materials.JQuejxSwmuFbDqi} />
          <mesh geometry={nodes.MdhDahfMTHTMOnv.geometry} material={materials.oXLVwLNmHxoKxYU} />
          <mesh geometry={nodes.CIKmzlWHngmAoKr.geometry} material={materials.oScFSXJqbuAqAHZ} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tablet-transformed.glb')
